import { credentials } from '@grpc/grpc-js';
import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { ControlClient, FleetClient } from '@platform/proto';
import * as fs from 'fs';
import { DockerService } from '../docker/docker.service';

export interface StartRunOptions {
  fabHash: string;
  fabContent: Buffer;
  overrideConfig?: Record<string, any>;
  federation?: string;
}

@Injectable()
export class FlowerService implements OnModuleInit {
  private readonly logger = new Logger(FlowerService.name);
  private fleetClient!: FleetClient;
  private controlClient!: ControlClient;

  constructor(
    private readonly configService: ConfigService,
    private readonly dockerService: DockerService,
  ) {}

  onModuleInit() {
    const grpcHost = this.configService.getOrThrow<string>('SUPERLINK_HOST');
    const certPath = this.configService.getOrThrow<string>('BACKEND_CERT_PATH');
    const keyPath = this.configService.getOrThrow<string>('BACKEND_KEY_PATH');
    const caPath = this.configService.getOrThrow<string>('BACKEND_CA_PATH');

    const rootCert = fs.readFileSync(caPath);
    const clientCert = fs.readFileSync(certPath);
    const clientKey = fs.readFileSync(keyPath);

    const sslCredentials = credentials.createSsl(
      rootCert,
      clientKey,
      clientCert,
    );

    this.fleetClient = new FleetClient(`${grpcHost}:9092`, sslCredentials);
    this.controlClient = new ControlClient(`${grpcHost}:9093`, sslCredentials);

    this.logger.log(`Flower gRPC clients initialized for ${grpcHost}`);
  }

  /**
   * Registers a SuperNode in the SuperLink using an OpenSSH public key.
   * The key MUST be exactly the content of a `.pub` file generated by ssh-keygen.
   *
   * Uses the Flower CLI (`flwr supernode register`) because the gRPC API requires
   * SuperNode authentication that administrative clients don't have.
   */
  async registerNode(sshPublicKey: string): Promise<number> {
    this.logger.debug('Registering SuperNode with SSH public key via CLI');

    const tmpKeyPath = `/tmp/node-${Date.now()}.pub`;

    try {
      await this.dockerService.execInContainer('superlink', [
        'sh',
        '-c',
        `printf '%s\n' "${sshPublicKey}" > ${tmpKeyPath}`,
      ]);

      const cmd = `cd /app && flwr supernode register --format json ${tmpKeyPath} . local-deployment`;
      this.logger.debug(`Executing command: ${cmd}`);

      const { stdout, stderr } = await this.dockerService.execInContainer(
        'superlink',
        ['sh', '-c', cmd],
      );

      this.logger.debug(`CLI stdout: ${stdout}`);
      if (stderr) {
        this.logger.debug(`CLI stderr: ${stderr}`);
      }

      // Clean up temporary key file
      await this.dockerService.execInContainer('superlink', [
        'sh',
        '-c',
        `rm -f ${tmpKeyPath}`,
      ]);

      // Parse the node ID from the JSON output
      try {
        const result = JSON.parse(stdout);
        const nodeId =
          result['node-id'] || result.node_id || result.nodeId || result.id;

        if (!nodeId) {
          throw new Error(
            `No node ID found in response: ${JSON.stringify(result)}`,
          );
        }

        this.logger.log(`SuperNode registered with ID ${nodeId}`);
        return nodeId;
      } catch (parseError) {
        // If JSON parsing fails, try the old regex pattern as fallback
        const match = stdout.match(/ID:\s*(\d+)/m);
        if (!match) {
          throw new Error(`Unable to parse node ID from output: ${stdout}`);
        }

        const nodeId = parseInt(match[1], 10);
        this.logger.log(`SuperNode registered with ID ${nodeId}`);
        return nodeId;
      }
    } catch (error) {
      this.logger.error('Failed to register SuperNode', error);
      throw error;
    }
  }

  async deactivateNode(nodeId: number): Promise<void> {
    return new Promise((resolve, reject) => {
      this.fleetClient.deactivateNode({ nodeId: String(nodeId) }, (error) => {
        if (error) {
          reject(error);
        } else {
          resolve();
        }
      });
    });
  }

  async startRun(options: StartRunOptions): Promise<string> {
    const request = {
      fab: {
        hashStr: options.fabHash,
        content: new Uint8Array(options.fabContent),
        verifications: {},
      },
      overrideConfig: options.overrideConfig || {},
      federation: options.federation || 'default',
      appSpec: '',
      federationOptions: { items: [] },
    };

    return new Promise((resolve, reject) => {
      this.controlClient.startRun(request, (error, response) => {
        if (error) {
          reject(error);
          return;
        }

        if (!response || response.runId === undefined) {
          reject(new Error('No runId returned'));
          return;
        }

        // runId can be either a number or a string (when > MAX_SAFE_INTEGER)
        // Just convert to string in both cases
        resolve(String(response.runId));
      });
    });
  }

  async stopRun(runId: number): Promise<boolean> {
    return new Promise((resolve, reject) => {
      this.controlClient.stopRun({ runId: String(runId) }, (error, response) => {
        if (error) {
          reject(error);
        } else {
          resolve(response.success);
        }
      });
    });
  }
}
