\set pgpass `echo "$POSTGRES_PASSWORD"`

DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'service_account') THEN
    CREATE USER service_account LOGIN;
  END IF;
END
$$;

ALTER USER service_account WITH PASSWORD :'pgpass';

GRANT CONNECT ON DATABASE postgres TO service_account;

GRANT USAGE ON SCHEMA public TO service_account;
GRANT USAGE ON SCHEMA auth TO service_account;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO service_account;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA auth TO service_account;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_account;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA auth TO service_account;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA auth TO service_account;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO service_account;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO service_account;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO service_account;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT EXECUTE ON FUNCTIONS TO service_account;

ALTER DEFAULT PRIVILEGES IN SCHEMA auth
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO service_account;

ALTER DEFAULT PRIVILEGES IN SCHEMA auth
  GRANT USAGE, SELECT ON SEQUENCES TO service_account;

ALTER DEFAULT PRIVILEGES IN SCHEMA auth
  GRANT EXECUTE ON FUNCTIONS TO service_account;

ALTER USER service_account BYPASSRLS;
