FROM node:25

WORKDIR /usr/src/app

RUN npm install -g pnpm \
  && apt-get update \
  && apt-get install -y protobuf-compiler python3 make g++ \
  && rm -rf /var/lib/apt/lists/*

CMD ["sh", "-c", "pnpm install && mkdir -p node_modules/.prisma && ln -sf ../../apps/backend/prisma/generated/client node_modules/.prisma/client && mkdir -p /usr/src/app/packages/proto/gen/ts && pnpm run --filter @platform/proto flower:proto && pnpm run dev:backend"]
