services:
  backend:
    image: platform-backend:latest
    build:
      context: ../
      dockerfile: apps/backend/docker/Dockerfile.dev
    volumes:
      - ../apps/backend:/usr/src/app/apps/backend
      - ../packages:/usr/src/app/packages
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"

  frontend:
    image: platform-frontend:latest
    build:
      context: ../
      dockerfile: apps/frontend/docker/Dockerfile.dev
    volumes:
      - ../apps/frontend:/usr/src/app/apps/frontend
      - ../packages:/usr/src/app/packages
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"

  websocket:
    image: platform-websocket:latest
    build:
      context: ../
      dockerfile: apps/websocket/docker/Dockerfile.dev
    volumes:
      - ../apps/websocket:/usr/src/app/apps/websocket
      - ../packages:/usr/src/app/packages
      - /usr/src/app/node_modules
    ports:
      - "3002:3002"

  supabase-db:
      image: supabase/postgres:17.6.1.054
      ports:
        - "54322:5432"
      volumes:
        - supabase_data:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres

  supabase-auth:
    image: supabase/gotrue:v2.183.0
    depends_on:
      - supabase-db
    ports:
      - "9999:9999"
    environment:
      GOTRUE_LOG_LEVEL: debug
      API_EXTERNAL_URL: http://localhost:9999
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_JWT_SECRET: 798c454d482c70fc7793fa3fc21ac657
      POSTGRES_PASSWORD: postgres
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://postgres:postgres@db:5432/postgres

  postgrest:
    image: postgrest/postgrest:v14.1
    depends_on:
      - supabase-db
    ports:
      - "3003:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@supabase-db:5432/postgres
      PGRST_DB_ANON_ROLE: postgres
      PGRST_JWT_SECRET: 0b6d688f04e9124f7906ff6661f74b2c

  localstack:
    image: localstack/localstack:s3-latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      AWS_DEFAULT_REGION: us-east-1
      DEBUG: 1
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  vault:
    image: hashicorp/vault:1.21
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/file

volumes:
  supabase_data:
  localstack_data:
  vault_data:
