export enum ErrorCode {
  TOKEN_NOT_PROVIDED = 'TOKEN_NOT_PROVIDED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',

  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  NOT_ORGANIZATION_MEMBER = 'NOT_ORGANIZATION_MEMBER',
  NOT_ORGANIZATION_OWNER = 'NOT_ORGANIZATION_OWNER',
  NOT_PROJECT_MEMBER = 'NOT_PROJECT_MEMBER',
}
