export enum ErrorCode {
  TOKEN_NOT_PROVIDED = 'TOKEN_NOT_PROVIDED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED',

  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  NOT_ORGANIZATION_MEMBER = 'NOT_ORGANIZATION_MEMBER',
  NOT_ORGANIZATION_OWNER = 'NOT_ORGANIZATION_OWNER',
  NOT_PROJECT_MEMBER = 'NOT_PROJECT_MEMBER',

  ORGANIZATION_NOT_FOUND = 'ORGANIZATION_NOT_FOUND',
  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  INVALID_INPUT = 'INVALID_INPUT',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
}
